
Note:<br/>
<li>注册成功后您需要下载客户端才能使用代理服务。</li>

<li>客户端为Python脚本需要安装Python2.6才能正常运行。</li>
<br/>
    
    <li><dt>客户端下载(当前版本0.01)</dt>
    <dd> <a href="PyProxyclient_CLI-0.01.py" target="_blank">PyProxy0.01 &nbsp;命令行版本</a>	</dd>
    <dd> <a href="PyProxyclient_GUI-0.01.py" target="_blank">PyProxy0.01 &nbsp;图形界面版本(需要wxPython)</a>	</dd>
     </li>
     <li><dt>相关软件下载</dt>
     <dd> <a href="http://www.python.org/download" target="_blank">Python</a></dd>
     <dd> <a href="http://www.wxpython.org/download.php" target="_blank">wxPython</a></dd>
	</li>